CLOCK_TICK = 0.01
BLOCK_SIZE = 20  # smallest block size

WIDTH_LIMIT = 600  # - W_LIMIT TO + W_LIMIT
HEIGHT_LIMIT = 300  # - H_LIMIT TO + H_LIMIT

PADDLE_HEIGHT = 100
PADDLE_HALF_HEIGHT = PADDLE_HEIGHT / 2
PADDLE_POS_X = WIDTH_LIMIT - 50  # POS_X is fixed. POS_Y will be moving

PADDLE_SPEED = 9
BALL_SPEED = 11

BALL_MIN_ANGLE = 27
BALL_MAX_ANGLE = 53

# COLORS ----- -----
PADDLE_COLOR = "#FFFAFA"  # snow
BALL_COLOR = "#6495ED"  # cornflower blue
BALL_HIT_COLOR = "#FFFAFA"  # snow
WALL_COLOR = "#FFFAFA"  # snow

